/**
 * @insimul/core zod schemas — runtime-validated transport shapes for the
 * engine-agnostic contract (US-CE4). These validate the SaveFile, its export
 * Envelope, and the World IR at trust boundaries (import/upload/export).
 *
 * The emitted JSON Schema counterparts live in `packages/core/schemas/` and are
 * regenerated by `npm run schemas` (see `scripts/emit-schemas.ts`); a drift
 * guard test fails if they fall out of sync with these definitions.
 */

export {
  saveFileSchema,
  worldSnapshotSchema,
  currentGameStateSchema,
  type SaveFileSchema,
} from './save-file.schema';
export { saveEnvelopeSchema, type SaveEnvelopeSchema } from './save-envelope.schema';
export { worldIrSchema, metaIrSchema, type WorldIrSchema } from './world-ir.schema';
