/**
 * Assessment Type Definitions
 *
 * Pure type definitions for in-game language proficiency assessments.
 * Assessments are structured as multi-phase encounters (e.g., Arrival/Departure)
 * with reading, writing, listening, and conversation sections scored across
 * multiple dimensions mapped to CEFR levels.
 */

// ───────────────────────────────────────────────────────────────────────────
// Core Enums & Literals
// ───────────────────────────────────────────────────────────────────────────

export type AssessmentType = 'arrival' | 'departure' | 'periodic' | 'npc_exam' | 'arrival_encounter' | 'departure_encounter';

export type PhaseType = 'reading' | 'writing' | 'listening' | 'initiate_conversation' | 'conversation';

/** @deprecated Use PhaseType directly */
export type AssessmentPhaseType = PhaseType;

export type TaskType =
  | 'reading_comprehension'
  | 'writing_prompt'
  | 'listening_comprehension'
  | 'conversation_quest'
  | 'object_recognition';

import type { CEFRLevel, CefrLevel } from '@shared/language/cefr';
export type { CEFRLevel, CefrLevel } from '@shared/language/cefr';

export type AssessmentStatus =
  | 'idle'
  | 'initializing'
  | 'phase_active'
  | 'phase_transitioning'
  | 'scoring'
  | 'complete'
  | 'pending'
  | 'in_progress'
  | 'completed'
  | 'abandoned';

export type ScoringMethod = 'llm' | 'automated';

// ───────────────────────────────────────────────────────────────────────────
// Scoring
// ───────────────────────────────────────────────────────────────────────────

export interface ScoringDimension {
  id: string;
  name: string;
  description: string;
  /** Min score for this dimension (typically 1) */
  minScore?: number;
  /** Max score for this dimension (typically 5) */
  maxScore: number;
}

export interface AssessmentDimensionScores {
  comprehension: number;   // 1-5
  fluency: number;         // 1-5
  vocabulary: number;      // 1-5
  grammar: number;         // 1-5
  pronunciation: number;   // 1-5
}

// ───────────────────────────────────────────────────────────────────────────
// Content Generation & Quest Config
// ───────────────────────────────────────────────────────────────────────────

/** A comprehension question used in reading/listening phases */
export interface AssessmentQuestion {
  id: string;
  /** The question text (may be generated by LLM at runtime) */
  questionText: string;
  /** Max points for this question */
  maxPoints: number;
}

/** Template that tells the LLM what kind of content to generate for a phase */
export interface ContentTemplate {
  /** Topic/scenario description for the LLM (e.g., "arriving in a new city, asking for directions") */
  topic: string;
  /** Target difficulty level */
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /** Approximate length in sentences for passages */
  lengthSentences?: number;
  /** Number of questions to generate (reading/listening) */
  questionCount?: number;
  /** Number of writing prompts to generate */
  promptCount?: number;
}

/** Config for the in-game conversation quest phase */
export interface ConversationQuestConfig {
  /** Minimum number of conversational exchanges */
  minExchanges: number;
  /** Maximum number of conversational exchanges */
  maxExchanges: number;
  /** Conversation topics to cover */
  topics: string[];
  /** NPC role description for system prompt */
  npcRole?: string;
}

// ───────────────────────────────────────────────────────────────────────────
// Task & Phase Definitions (static encounter structure)
// ───────────────────────────────────────────────────────────────────────────

export interface AssessmentTask {
  id: string;
  name?: string;
  description?: string;
  type?: TaskType;
  /** Template prompt — may contain {{targetLanguage}}, {{cityName}} placeholders */
  prompt: string;
  /** Max points for this task */
  maxPoints?: number;
  /** Max score (alias for maxPoints used by periodic encounters) */
  maxScore?: number;
  /** How this task is scored */
  scoringMethod?: ScoringMethod;
  /** Scoring dimensions for this task */
  scoringDimensions?: ScoringDimension[];
  /** Time limit in seconds (optional) */
  timeLimitSeconds?: number;
  /** Template for LLM content generation (reading/writing/listening) */
  contentTemplate?: ContentTemplate;
  /** Reading/listening passage text (populated at runtime by LLM) */
  passage?: string;
  /** Comprehension questions (populated at runtime by LLM for reading/listening) */
  questions?: AssessmentQuestion[];
  /** Writing prompts (populated at runtime by LLM) */
  writingPrompts?: string[];
  /** Config for conversation quest phase */
  questConfig?: ConversationQuestConfig;
}

export interface AssessmentPhase {
  id: string;
  type: PhaseType | AssessmentPhaseType;
  name: string;
  description: string;
  tasks: AssessmentTask[];
  /** Max points for the entire phase (sum of task maxPoints) */
  maxPoints?: number;
  /** Max score (alias for maxPoints used by periodic encounters) */
  maxScore?: number;
  /** Time limit for the entire phase in seconds (optional) */
  timeLimitSeconds?: number;
  /** Scoring dimensions evaluated during this phase */
  scoringDimensions?: string[] | ScoringDimension[];
  /** NPC system prompt template (uses {{targetLanguage}}, {{cityName}}) */
  systemPromptTemplate?: string;
}

export interface AssessmentDefinition {
  id: string;
  type: AssessmentType;
  name: string;
  description: string;
  /** Target language placeholder — replaced at runtime */
  targetLanguage?: string;
  phases: AssessmentPhase[];
  /** Total max points across all phases */
  totalMaxPoints: number;
  /** Scoring dimensions used in this assessment */
  scoringDimensions?: ScoringDimension[];
  /** Estimated duration in minutes */
  estimatedMinutes?: number;
  /** Time limit in seconds (used by periodic encounters) */
  timeLimitSeconds?: number;
}

// ───────────────────────────────────────────────────────────────────────────
// Runtime Results
// ───────────────────────────────────────────────────────────────────────────

export interface RecordingReference {
  /** Storage key or URL for the recording */
  storageKey?: string;
  /** URL for the recording */
  url?: string;
  /** MIME type (e.g., 'audio/webm', 'text/plain') */
  mimeType?: string;
  /** Duration in seconds (for audio/video) */
  durationSeconds?: number;
  /** Phase this recording belongs to */
  phaseId: string;
  /** Task this recording belongs to (optional) */
  taskId?: string;
  /** Timestamp when recorded */
  recordedAt?: string;
  /** Transcript of the recording */
  transcript?: string;
}

export interface TranscriptEntry {
  role: 'player' | 'npc' | 'system';
  text: string;
  timestamp: number;
  phaseId: string;
  taskId?: string;
}

export interface AutomatedMetrics {
  /** Words per minute */
  wpm?: number;
  wordsPerMinute?: number;
  /** Type-token ratio (vocabulary diversity) */
  ttr?: number;
  typeTokenRatio?: number;
  /** Mean length of utterance in words */
  mlu?: number;
  meanLengthUtterance?: number;
  /** Average response latency in milliseconds */
  avgLatencyMs?: number;
  responseLatencyMs?: number;
  /** Number of self-repairs/corrections */
  repairs?: number;
  selfRepairs?: number;
  /** Number of code-switching instances (falling back to L1) */
  codeSwitchingCount?: number;
  codeSwitchCount?: number;
}

export interface TaskResult {
  taskId: string;
  /** Points earned */
  score: number;
  /** Max possible points */
  maxPoints?: number;
  /** Max score (alias for maxPoints) */
  maxScore?: number;
  /** Per-dimension scores */
  dimensionScores?: Record<string, number>;
  /** Player's raw response (text input, selection, etc.) */
  playerResponse?: string;
  /** Scoring rationale (from LLM or auto-scorer) */
  rationale?: string;
}

export interface PhaseResult {
  phaseId: string;
  /** Total score for this phase */
  score?: number;
  totalScore?: number;
  /** Max possible score for this phase */
  maxPoints?: number;
  maxScore?: number;
  /** Individual task results */
  taskResults: TaskResult[];
  /** Per-dimension scores (dimension id -> score) */
  dimensionScores?: Record<string, number>;
  /** Automated metrics collected during this phase */
  automatedMetrics?: AutomatedMetrics;
  /** Full transcript of the phase interaction (string or structured entries) */
  transcript?: string | TranscriptEntry[];
  /** Recording references for this phase */
  recordings?: RecordingReference[];
  /** When this phase started */
  startedAt?: string;
  /** When this phase completed */
  completedAt?: string | number;
}

export interface AssessmentResult {
  sessionId: string;
  assessmentType: AssessmentType;
  totalScore: number;
  maxScore: number;
  cefrLevel: CEFRLevel;
  phaseResults: PhaseResult[];
  dimensionScores?: AssessmentDimensionScores;
  completedAt: number;
}

export interface AssessmentSession {
  id: string;
  playerId: string;
  worldId: string;
  playthroughId?: string;
  /** Which assessment definition was used */
  assessmentDefinitionId?: string;
  definitionId?: string;
  assessmentType: AssessmentType;
  /** Target language being assessed */
  targetLanguage?: string;
  status?: AssessmentStatus;
  /** Results per phase */
  phaseResults: PhaseResult[];
  /** Total score across all phases */
  totalScore?: number;
  /** Total max possible score */
  totalMaxPoints: number;
  /** Overall CEFR level determined from scores */
  cefrLevel?: CEFRLevel | string;
  /** Aggregate dimension scores (dimension id -> score) */
  dimensionScores?: Record<string, number>;
  /** Aggregate automated metrics */
  automatedMetrics?: AutomatedMetrics;
  /** All recordings for this session */
  recordings?: RecordingReference[];
  /** Full conversation transcript */
  transcript?: Array<{ role: 'player' | 'npc'; text: string; timestamp: number }>;
  /** When the session was created */
  createdAt?: string;
  /** When the session started (first phase began) */
  startedAt?: string | number;
  /** When the session completed */
  completedAt?: string | number;
}

// ───────────────────────────────────────────────────────────────────────────
// Assessment Modal UI Config
// ───────────────────────────────────────────────────────────────────────────

// ───────────────────────────────────────────────────────────────────────────
// Quest-Embedded Assessment Types (stored in quest customData.assessment)
// ───────────────────────────────────────────────────────────────────────────

/**
 * A single task result storing the player's answer and score.
 * Stored in quest overlay phaseResults.
 */
export interface AssessmentTaskResult {
  taskId: string;
  playerAnswer: string;
  score: number;
  maxPoints: number;
  /** LLM grader rationale for this task. Present for conversation/writing
   *  phases graded server-side; absent for offline/heuristic paths. Carried
   *  through to the Playthroughs view so world owners can see why the grade
   *  landed where it did. */
  rationale?: string;
  /** For conversation-phase turns only: the NPC utterance the player was
   *  responding to, so the view can reconstruct the exchange. */
  npcPrompt?: string;
  /** False when this turn fell back to the neutral estimate (grader failed). */
  graded?: boolean;
}

/**
 * Result for a single assessment phase, stored in quest overlay.
 * Contains player answers and scores for each task in the phase.
 */
export interface AssessmentPhaseResult {
  phaseId: string;
  score: number;
  maxScore: number;
  taskResults: AssessmentTaskResult[];
  dimensionScores: Record<string, number>;
  completedAt: string;
}

/**
 * Final assessment completion result stored in quest overlay.
 * Computed client-side when all phase objectives are complete.
 */
export interface AssessmentCompletionResult {
  totalScore: number;
  maxScore: number;
  cefrLevel: CEFRLevel;
  dimensionScores: Record<string, number>;
  completedAt: string;
}

/**
 * Assessment data embedded in quest customData.assessment.
 * Matches the shape of AssessmentDefinition so the UI can consume it
 * without changes, but lives entirely within the quest document.
 */
export interface AssessmentQuestData {
  assessmentType: AssessmentType;
  totalMaxPoints: number;
  estimatedMinutes: number;
  phases: AssessmentQuestPhase[];
}

/**
 * A phase within an AssessmentQuestData, containing pre-generated content.
 */
export interface AssessmentQuestPhase {
  id: string;
  type: PhaseType;
  name: string;
  tasks: AssessmentQuestTask[];
  maxScore: number;
  scoringDimensions: ScoringDimension[];
}

/**
 * A task within an assessment quest phase.
 * Includes both the template definition and any pre-generated content
 * (passage, questions, writingPrompts) baked in at world creation time.
 */
export interface AssessmentQuestTask {
  id: string;
  type: TaskType;
  prompt: string;
  maxPoints: number;
  scoringMethod: ScoringMethod;
  scoringDimensions: ScoringDimension[];
  contentTemplate?: ContentTemplate;
  /** Pre-generated reading/listening passage (populated at world creation) */
  passage?: string;
  /** Pre-generated comprehension questions (populated at world creation) */
  questions?: AssessmentQuestion[];
  /** Pre-generated writing prompts (populated at world creation) */
  writingPrompts?: string[];
  /** Config for conversation quest phase */
  questConfig?: ConversationQuestConfig;
}

// ───────────────────────────────────────────────────────────────────────────
// Assessment Modal UI Config
// ───────────────────────────────────────────────────────────────────────────

/** Configuration for the assessment modal (reading/writing/listening phases). */
export interface AssessmentModalConfig {
  phaseType: 'reading' | 'writing' | 'listening';
  phaseName: string;
  phaseIndex: number;
  totalPhases: number;
  /** Reading/listening passage text (in target language) */
  passage?: string;
  /** Comprehension questions for reading/listening */
  questions?: Array<{ id: string; questionText: string; maxPoints: number }>;
  /** Writing prompts */
  writingPrompts?: string[];
  /** Audio URL for listening section (TTS-generated) */
  audioUrl?: string;
  /** Target language code for browser TTS fallback (e.g. 'fr', 'es') */
  targetLanguage?: string;
  /** Server TTS function — returns an audio Blob for natural-sounding speech. Falls back to browser TTS if not provided. */
  synthesizeSpeech?: (text: string, language: string) => Promise<Blob | null>;
  /** Called when the player submits their answers */
  onSubmit: (answers: Record<string, string>) => void;
}
