/**
 * Helper Predicates for Prolog KB
 *
 * Base Prolog helper rules that action prerequisites can reference.
 * Loaded into GamePrologEngine at initialization before action definitions.
 *
 * Includes:
 *   - CEFR level comparison (cefr_gte/2)
 *   - Weapon/tool type classification (is_weapon_type/2, is_tool_type/2)
 *   - Skill tier naming and comparison (skill_tier_name/2, skill_gte/3)
 */

export const HELPER_PREDICATES_PROLOG = `
% ═══════════════════════════════════════════════════════════════════════════
% Helper Predicates — base rules for action prerequisite evaluation
% ═══════════════════════════════════════════════════════════════════════════

% ── CEFR Level Comparison ─────────────────────────────────────────────────
% Maps CEFR language proficiency levels to integer ranks for comparison.
% Usage: cefr_gte(ActualLevel, RequiredLevel) succeeds if ActualLevel >= RequiredLevel

cefr_level_rank(a1, 1).
cefr_level_rank(a2, 2).
cefr_level_rank(b1, 3).
cefr_level_rank(b2, 4).
cefr_level_rank(c1, 5).
cefr_level_rank(c2, 6).

cefr_gte(Actual, Required) :-
  cefr_level_rank(Actual, AR),
  cefr_level_rank(Required, RR),
  AR >= RR.

% ── Weapon Type Classification ────────────────────────────────────────────
% Checks if an item is a weapon of a given type.
% Requires item_type/2 facts to be asserted for items in the KB.

:- dynamic(item_type/2).

is_weapon_type(ItemId, sword) :- item_type(ItemId, sword).
is_weapon_type(ItemId, axe) :- item_type(ItemId, axe).
is_weapon_type(ItemId, bow) :- item_type(ItemId, bow).
is_weapon_type(ItemId, staff) :- item_type(ItemId, staff).
is_weapon_type(ItemId, pistol) :- item_type(ItemId, pistol).

% ── Tool Type Classification ──────────────────────────────────────────────
% Checks if an item is a tool of a given type.

is_tool_type(ItemId, fishing_rod) :- item_type(ItemId, fishing_rod).
is_tool_type(ItemId, pickaxe) :- item_type(ItemId, pickaxe).
is_tool_type(ItemId, axe) :- item_type(ItemId, axe).
is_tool_type(ItemId, hoe) :- item_type(ItemId, hoe).

% ── Skill Tier Names ──────────────────────────────────────────────────────
% Maps integer skill levels to human-readable tier names.

skill_tier_name(1, novice).
skill_tier_name(2, novice).
skill_tier_name(3, apprentice).
skill_tier_name(4, apprentice).
skill_tier_name(5, journeyman).
skill_tier_name(6, journeyman).
skill_tier_name(7, expert).
skill_tier_name(8, expert).
skill_tier_name(9, expert).
skill_tier_name(10, master).

% ── Skill Level Comparison ────────────────────────────────────────────────
% Succeeds if Actor has Skill at Level >= MinLevel.

skill_gte(Actor, Skill, MinLevel) :-
  has_skill(Actor, Skill, Level),
  Level >= MinLevel.

% ═══════════════════════════════════════════════════════════════════════════
% Quest Objective Completion Rules
% ═══════════════════════════════════════════════════════════════════════════
%
% Bridge between quest_objective/3 goals (generated by quest-converter.ts)
% and game facts asserted by GamePrologEngine at runtime.
%
% objective_complete(Player, QuestId, ObjIndex) succeeds when the game state
% satisfies the objective goal stored in quest_objective(QuestId, ObjIndex, Goal).
%
% This is the critical link that makes quest_complete/2 work:
%   quest_complete(Player, QuestId) :-
%       \\+ (quest_objective(QuestId, Idx, _), \\+ objective_complete(Player, QuestId, Idx)).

:- dynamic(collected/3).
:- dynamic(has/2).
:- dynamic(has_item/3).
:- dynamic(visited/2).
:- dynamic(discovered/2).
:- dynamic(talked_to/3).
:- dynamic(delivered/3).
:- dynamic(defeated/2).
:- dynamic(crafted/3).
:- dynamic(vocab_used/3).
:- dynamic(puzzle_solved/2).
:- dynamic(reputation_change/3).
:- dynamic(escorted/3).
:- dynamic(quest_progress/3).
:- dynamic(quest_objective/3).
:- dynamic(objective_complete/3).
:- dynamic(text_found/2).
:- dynamic(text_read/2).
:- dynamic(sign_read/2).
:- dynamic(scene_described/2).
:- dynamic(response_written/2).
:- dynamic(translation_completed/2).
:- dynamic(pronunciation_passed/2).
:- dynamic(photo_taken/2).
:- dynamic(object_examined/2).
:- dynamic(object_identified/2).
:- dynamic(object_pointed_named/2).
:- dynamic(direction_step_done/2).
:- dynamic(gift_given/3).
:- dynamic(food_ordered/2).
:- dynamic(price_haggled/2).
:- dynamic(npc_conversation_turns/3).
:- dynamic(action_performed/2).
:- dynamic(action_completes_objective/2).
:- dynamic(physical_action_done/2).
:- dynamic(conversational_action/4).
:- dynamic(comprehension_done/2).
:- dynamic(used/2).
:- dynamic(purchased/3).
:- dynamic(sold/3).
:- dynamic(combat_action_done/3).
:- dynamic(activity_observed/3).
:- dynamic(assessment_phase_done/4).
:- dynamic(friendship_tier/3).
:- dynamic(assessment_completed/2).

% ── Radiant quest generation (runtime provenance + cooldown bookkeeping) ──
% Asserted by the radiant slot-filling engine when it emits a quest, and
% persisted into save.currentState.prologFacts. Declared dynamic so the engine
% can assert/retract them and so the save-restore fact validator recognises
% them. The authored template predicates (radiant_template/2 etc.) are
% consulted from world data and catalogued in predicate-schema.ts instead.
:- dynamic(radiant_generated/3).
:- dynamic(radiant_cooldown_until/2).

% ── Collection objectives ────────────────────────────────────────────────
% collect(Item, Count) — player collected enough of an item
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, collect(Item, Count)),
    collected(Player, Item, Qty),
    Qty >= Count.

% collect with unspecified item — count total unique items collected
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, collect('', Count)),
    aggregate_all(count, collected(Player, _, _), Total),
    Total >= Count.

% ── Visit location ───────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, visit_location(Location)),
    visited(Player, Location).

% visit_location with empty target — any visit counts
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, visit_location('')),
    visited(Player, _).

% ── Discover location ────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, discover_location(Location)),
    discovered(Player, Location).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, discover_location('')),
    discovered(Player, _).

% ── Talk to NPC ──────────────────────────────────────────────────────────
% talk_to(NPC) — single conversation
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, talk_to(NPC)),
    talked_to(Player, NPC, _).

% talk_to(NPC, RequiredTurns) — conversation with minimum turns
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, talk_to(NPC, RequiredTurns)),
    talked_to(Player, NPC, Turns),
    Turns >= RequiredTurns.

% talk_to with empty NPC — any NPC conversation counts
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, talk_to('')),
    talked_to(Player, _, _).

% ── Conversation turns (aggregate) ──────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, conversation_turns(RequiredTurns)),
    aggregate_all(sum(T), talked_to(Player, _, T), Total),
    Total >= RequiredTurns.

% Also support npc_conversation_turns for more granular tracking
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, conversation_turns(RequiredTurns)),
    aggregate_all(sum(T), npc_conversation_turns(Player, _, T), Total),
    Total >= RequiredTurns.

% ── Deliver item ─────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, deliver(Item, NPC)),
    delivered(Player, NPC, Item).

% ── Defeat enemies ───────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, defeat(EnemyType, Count)),
    aggregate_all(count, defeated(Player, EnemyType), Total),
    Total >= Count.

% defeat with empty type — any enemy counts
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, defeat('', Count)),
    aggregate_all(count, defeated(Player, _), Total),
    Total >= Count.

% ── Vocabulary / learn words ─────────────────────────────────────────────
% learn_words_count(Count) — player used enough distinct vocabulary words
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, learn_words_count(Count)),
    aggregate_all(count, vocab_used(Player, _, 1), Total),
    Total >= Count.

% learn_words([WordList]) — player used specific words
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, learn_words(WordList)),
    is_list(WordList),
    forall(member(Word, WordList), vocab_used(Player, Word, _)).

% ── Grammar practice ─────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, practice_grammar(_, Count)),
    quest_progress(Player, QuestId, Progress),
    Progress >= Count.

% ── Craft item ───────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, craft_item(Item, Count)),
    crafted(Player, Item, Qty),
    Qty >= Count.

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, craft_item('', Count)),
    aggregate_all(sum(Q), crafted(Player, _, Q), Total),
    Total >= Count.

% ── Escort NPC ───────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, escort(NPC, Dest)),
    escorted(Player, NPC, Dest).

% ── Reputation ───────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, gain_reputation(Faction, Amount)),
    aggregate_all(sum(D), reputation_change(Player, Faction, D), Total),
    Total >= Amount.

% ── Solve puzzle ─────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, solve_puzzle(PuzzleId)),
    puzzle_solved(Player, PuzzleId).

% ── Use item ─────────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, use_item(Item)),
    used(Player, Item).

% ── Reach skill level ────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, reach_level(Skill, Level)),
    has_skill(Player, Skill, CurrentLevel),
    CurrentLevel >= Level.

% ── Survive duration ─────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, survive(Duration)),
    survived(Player, ActualDuration),
    ActualDuration >= Duration.

% ── Find text / read text (language learning) ────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, find_text(TextId)),
    text_found(Player, TextId).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, read_text(TextId)),
    text_read(Player, TextId).

% ── Examine object ──────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, examine_object(Count)),
    aggregate_all(count, object_examined(Player, _), Total),
    Total >= Count.

% ── Read sign ───────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, read_sign(Count)),
    aggregate_all(count, sign_read(Player, _), Total),
    Total >= Count.

% ── Write response / describe scene ─────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, write_response(Count)),
    aggregate_all(count, response_written(Player, _), Total),
    Total >= Count.

% ── Listen and repeat ───────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, listen_and_repeat(Count)),
    aggregate_all(count, pronunciation_passed(Player, _), Total),
    Total >= Count.

% ── Pronunciation check ─────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, pronunciation_check(Count)),
    aggregate_all(count, pronunciation_passed(Player, _), Total),
    Total >= Count.

% ── Identify / point-and-name ───────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, identify_object(Count)),
    aggregate_all(count, object_pointed_named(Player, _), Total),
    Total >= Count.

% ── Order food ──────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, order_food(Count)),
    aggregate_all(count, food_ordered(Player, _), Total),
    Total >= Count.

% ── Haggle price ────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, haggle_price(Count)),
    aggregate_all(count, price_haggled(Player, _), Total),
    Total >= Count.

% ── Buy item ────────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, buy_item(Count)),
    aggregate_all(count, action_performed(Player, buy_item), Total),
    Total >= Count.

% ── Sell item ───────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, sell_item(Count)),
    aggregate_all(count, action_performed(Player, sell_item), Total),
    Total >= Count.

% ── Give gift ───────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, give_gift(NPC)),
    NPC \\= any,
    gift_given(Player, NPC, _).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, give_gift(any)),
    gift_given(Player, _, _).

% ── Photograph subject ──────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, photograph(Subject, Count)),
    Subject \\= any,
    aggregate_all(count, photo_taken(Player, Subject), Total),
    Total >= Count.

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, photograph(any, Count)),
    aggregate_all(count, photo_taken(Player, _), Total),
    Total >= Count.

% ── Physical action ─────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, physical_action(Action, Count)),
    Action \\= '',
    aggregate_all(count, physical_action_done(Player, Action), Total),
    Total >= Count.

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, physical_action('', Count)),
    aggregate_all(count, physical_action_done(Player, _), Total),
    Total >= Count.

% ── Introduce self ──────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, introduce_self),
    conversational_action(Player, _, introduce_self, _).

% ── Ask for directions ──────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, ask_for_directions(Count)),
    aggregate_all(count, action_performed(Player, ask_for_directions), Total),
    Total >= Count.

% ── Comprehension quiz ──────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, comprehension_quiz(Count)),
    aggregate_all(count, comprehension_done(Player, _), Total),
    Total >= Count.

% ── Translation challenge ───────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, translation_challenge(Count)),
    aggregate_all(count, translation_completed(Player, correct), Total),
    Total >= Count.

% ── Follow directions ───────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, follow_directions(Count)),
    aggregate_all(count, direction_step_done(Player, QuestId, _), Total),
    Total >= Count.

% ── Listening comprehension ─────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, listening_comprehension(Count)),
    aggregate_all(count, pronunciation_passed(Player, _), Total),
    Total >= Count.

% ── Collect vocabulary ──────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, collect_vocabulary(Count)),
    aggregate_all(count, vocab_used(Player, _, _), Total),
    Total >= Count.

% ── Eavesdrop ───────────────────────────────────────────────────────────
:- dynamic(overheard_conversation/4).
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, eavesdrop(Topic)),
    overheard_conversation(Player, _, _, Topic).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, eavesdrop),
    overheard_conversation(Player, _, _, _).

% ── Build friendship ────────────────────────────────────────────────────
:- dynamic(friendship_level/3).
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, build_friendship(Count)),
    aggregate_all(count, (friendship_level(Player, _, Level), Level >= 3), Total),
    Total >= Count.

% ── Collect clue ────────────────────────────────────────────────────────
:- dynamic(clue_found/2).
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, collect_clue(Count)),
    aggregate_all(count, clue_found(Player, _), Total),
    Total >= Count.

% ── Assessment objectives ───────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, complete_assessment),
    assessment_result(Player, _, _, _, _, _).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, assessment_phase(PhaseType, _Trigger)),
    quest_progress(Player, QuestId, Progress),
    Progress >= 100.

% ── Meta / aggregation objectives (chapter quests) ──────────────────────
% vocabulary_activities(Count) — player completed enough vocab-related actions
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, vocabulary_activities(Count)),
    aggregate_all(count, (vocab_used(Player, _, _) ; object_pointed_named(Player, _)), Total),
    Total >= Count.

% conversation_activities(Count) — player had enough conversations
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, conversation_activities(Count)),
    aggregate_all(sum(T), talked_to(Player, _, T), Total),
    Total >= Count.

% grammar_activities(Count) — player practiced grammar enough times
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, grammar_activities(Count)),
    quest_progress(Player, QuestId, Progress),
    Progress >= Count.

% sustained_conversation(Count) — long conversation turns
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, sustained_conversation(Count)),
    npc_conversation_turns(Player, _, Turns),
    Turns >= Count.

% master_words(Count) — vocab words used correctly multiple times
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, master_words(Count)),
    aggregate_all(count, vocab_used(Player, _, 1), Total),
    Total >= Count.

% learn_new_words(Count) — distinct vocab words encountered
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, learn_new_words(Count)),
    aggregate_all(count, vocab_used(Player, _, _), Total),
    Total >= Count.

% find_vocabulary_items(Count) — objects examined/identified for vocab
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, find_vocabulary_items(Count)),
    aggregate_all(count, (object_examined(Player, _) ; object_pointed_named(Player, _)), Total),
    Total >= Count.

% ── Equip item ──────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, equip_item(Item)),
    Item \\= any,
    equipped(Player, Item, _).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, equip_item(any)),
    equipped(Player, _, _).

% ── Drop item ───────────────────────────────────────────────────────────
:- dynamic(dropped/2).
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, drop_item(Item)),
    Item \\= any,
    action_performed(Player, drop_item).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, drop_item(any)),
    action_performed(Player, drop_item).

% ── Combat action (individual moves) ───────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, combat_action(Count)),
    aggregate_all(count, combat_action_done(Player, _, _), Total),
    Total >= Count.

% ── Accept quest ────────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, accept_quest(TargetQuestId)),
    TargetQuestId \\= any,
    quest_active(Player, TargetQuestId).

objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, accept_quest(any)),
    quest_active(Player, _).

% ── Observe activity ────────────────────────────────────────────────────
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, observe_activity(Count)),
    aggregate_all(count, activity_observed(Player, _, _), Total),
    Total >= Count.

% ── Generic description-based objectives ─────────────────────────────────
% Fallback: if quest_progress has been tracked for this quest, check it
objective_complete(Player, QuestId, Idx) :-
    quest_objective(QuestId, Idx, objective(_)),
    quest_progress(Player, QuestId, Progress),
    Progress >= 100.

% ── All-objectives-complete meta-rule ────────────────────────────────────
% Used by quest_complete when completionCriteria is 'all_objectives'
all_objectives_done(Player, QuestId) :-
    \\+ (quest_objective(QuestId, Idx, _),
         \\+ objective_complete(Player, QuestId, Idx)).

% ═══════════════════════════════════════════════════════════════════════════
% Quest Status & Prerequisite System
% ═══════════════════════════════════════════════════════════════════════════
%
% quest_status/3 bridges the lifecycle facts asserted by GamePrologEngine
% (quest_active/2, quest_completed/2, quest_failed/2, quest_abandoned/2)
% to the status checks used by quest_available/2 rules.

:- dynamic(quest_active/2).
:- dynamic(quest_completed/2).
:- dynamic(quest_failed/2).
:- dynamic(quest_abandoned/2).
:- dynamic(quest_status/3).

% Derive quest_status from lifecycle facts if not directly asserted
quest_status(Player, QuestId, active) :-
    quest_active(Player, QuestId).
quest_status(Player, QuestId, completed) :-
    quest_completed(Player, QuestId).
quest_status(Player, QuestId, failed) :-
    quest_failed(Player, QuestId).
quest_status(Player, QuestId, abandoned) :-
    quest_abandoned(Player, QuestId).

% ── Cross-quest prerequisite checking ────────────────────────────────────
% all_prereqs_met(Player, QuestId) succeeds if every prerequisite quest
% has been completed by the player.
all_prereqs_met(Player, QuestId) :-
    \\+ (quest_prerequisite(QuestId, PrereqId),
         PrereqId \\= none,
         \\+ quest_status(Player, PrereqId, completed)).

% ── Quest chain ordering ─────────────────────────────────────────────────
% next_in_chain(Player, QuestId) — the next quest in a chain the player
% can take (all prior chain quests completed).
next_in_chain(Player, QuestId) :-
    quest_chain(QuestId, ChainId),
    quest_chain_order(QuestId, Order),
    PrevOrder is Order - 1,
    (PrevOrder < 0 ->
        true  % first quest in chain
    ;
        quest_chain_order(PrevQuest, PrevOrder),
        quest_chain(PrevQuest, ChainId),
        quest_status(Player, PrevQuest, completed)
    ).

% ── Conditional reward evaluation ────────────────────────────────────────
% quest_bonus_reward(Player, QuestId, RewardType, Value) — additional
% rewards granted based on how the quest was completed.
:- dynamic(quest_bonus_reward/4).

% Bonus for completing all objectives (not just the minimum)
quest_bonus_reward(Player, QuestId, bonus_xp, 50) :-
    all_objectives_done(Player, QuestId).

% Bonus for completing a quest chain
quest_bonus_reward(Player, QuestId, chain_complete_xp, BonusXP) :-
    quest_chain(QuestId, ChainId),
    chain_bonus_xp(ChainId, BonusXP),
    \\+ (quest_chain(OtherQuest, ChainId),
         OtherQuest \\= QuestId,
         \\+ quest_status(Player, OtherQuest, completed)).

:- dynamic(chain_bonus_xp/2).

% ── Reconciliation helpers ───────────────────────────────────────────────
% quest_should_be_complete(Player, QuestId) — Prolog believes this quest
% is done based on game state, even if not yet marked as completed.
quest_should_be_complete(Player, QuestId) :-
    quest_active(Player, QuestId),
    all_objectives_done(Player, QuestId).

% ═══════════════════════════════════════════════════════════════════════════
% Reputation Aggregation
% ═══════════════════════════════════════════════════════════════════════════
% reputation(Player, Faction, Total) — sums all reputation_change/3 facts.

:- dynamic(reputation_record/3).

reputation(Player, Faction, Total) :-
    aggregate_all(sum(D), reputation_change(Player, Faction, D), Total).
reputation(Player, Faction, 0) :-
    \\+ reputation_change(Player, Faction, _).

% reputation_at_least(Player, Faction, MinRep) — convenience check
reputation_at_least(Player, Faction, MinRep) :-
    reputation(Player, Faction, Rep),
    Rep >= MinRep.

% ═══════════════════════════════════════════════════════════════════════════
% Text & Reading Helpers
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(game_text/1).
:- dynamic(text_title/2).
:- dynamic(text_category/2).
:- dynamic(text_cefr_level/2).
:- dynamic(text_spawn_location/2).
:- dynamic(text_chapter/2).
:- dynamic(text_clue/2).
:- dynamic(text_vocabulary/4).

% text_available_at(TextId, LocationType) — texts that can appear at a location type
text_available_at(TextId, LocationType) :-
    game_text(TextId),
    text_spawn_location(TextId, LocationType).

% text_for_level(TextId, CefrLevel) — texts appropriate for a CEFR level
text_for_level(TextId, Level) :-
    game_text(TextId),
    text_cefr_level(TextId, Level).

% text_has_clue(TextId) — texts that reveal main quest clues
text_has_clue(TextId) :-
    text_clue(TextId, _).

% ═══════════════════════════════════════════════════════════════════════════
% Container Helpers
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(container/1).
:- dynamic(container_type/2).
:- dynamic(container_locked/1).
:- dynamic(container_key/2).
:- dynamic(container_contains/3).
:- dynamic(container_at_business/2).
:- dynamic(container_at_residence/2).

% container_accessible(Player, ContainerId) — can the player open this container?
container_accessible(Player, ContainerId) :-
    container(ContainerId),
    \\+ container_locked(ContainerId).
container_accessible(Player, ContainerId) :-
    container(ContainerId),
    container_locked(ContainerId),
    container_key(ContainerId, KeyItem),
    has(Player, KeyItem).

% ═══════════════════════════════════════════════════════════════════════════
% Residence & NPC Location Helpers
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(residence/1).
:- dynamic(residence_owner/2).
:- dynamic(lives_at/2).
:- dynamic(home/2).
:- dynamic(workplace/2).
:- dynamic(friends/2).
:- dynamic(coworker/2).
:- dynamic(enemies/2).
:- dynamic(knows/2).
:- dynamic(knows/3).
:- dynamic(believes/3).

:- dynamic(physical_trait/2).
:- dynamic(physical_trait/3).
:- dynamic(mental_trait/2).
:- dynamic(mental_trait/3).
:- dynamic(social_attribute/3).
:- dynamic(has_thought/2).
:- dynamic(believes_about/3).
:- dynamic(believes_about/4).
:- dynamic(college_graduate/1).
:- dynamic(retired/1).
:- dynamic(departure_year/2).
:- dynamic(current_location/2).
:- dynamic(character_status/2).

% ═══════════════════════════════════════════════════════════════════════════
% Public Building Helpers
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(public_building/1).
:- dynamic(public_building_name/2).
:- dynamic(public_building_type/2).
:- dynamic(public_building_of_settlement/2).
:- dynamic(public_building_on_lot/2).
:- dynamic(public_building_operational/2).
:- dynamic(public_building_capacity/2).
:- dynamic(public_building_employee/2).

% Find buildings of a specific type in a settlement
public_building_in(SettlementId, BuildingId, Type) :-
    public_building(BuildingId),
    public_building_of_settlement(BuildingId, SettlementId),
    public_building_type(BuildingId, Type).

% Check if a public building is operational
building_open(BuildingId) :-
    public_building(BuildingId),
    public_building_operational(BuildingId, true).

% ═══════════════════════════════════════════════════════════════════════════
% Settlement Detail Helpers
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(settlement_district/2).
:- dynamic(settlement_street/2).
:- dynamic(settlement_landmark/2).
:- dynamic(landmark_type/2).
:- dynamic(settlement_unemployed_count/2).
:- dynamic(settlement_deceased_count/2).
:- dynamic(settlement_vacant_lots/2).

% ═══════════════════════════════════════════════════════════════════════════
% Country & State Relationship Helpers
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(country_ally/2).
:- dynamic(country_enemy/2).
:- dynamic(country_culture/3).
:- dynamic(cultural_value/3).
:- dynamic(country_law/2).
:- dynamic(social_structure/3).
:- dynamic(state_governor/2).
:- dynamic(state_local_government/2).
:- dynamic(state_previous_country/2).

% countries_at_war(A, B) — bidirectional enemy check
countries_at_war(A, B) :- country_enemy(A, B).
countries_at_war(A, B) :- country_enemy(B, A).

% countries_allied(A, B) — bidirectional alliance check
countries_allied(A, B) :- country_ally(A, B).
countries_allied(A, B) :- country_ally(B, A).

% npc_at_home(NpcId) — NPC is currently at their home residence
npc_at_home(NpcId) :-
    home(NpcId, ResId),
    current_location(NpcId, ResId).

% npc_at_work(NpcId) — NPC is currently at their workplace
npc_at_work(NpcId) :-
    workplace(NpcId, WorkId),
    current_location(NpcId, WorkId).

% lives_near(Char1, Char2) — two characters share the same residence
lives_near(Char1, Char2) :-
    lives_at(Char1, Res),
    lives_at(Char2, Res),
    Char1 \\= Char2.

% knows_about(NpcId, Topic) — NPC has knowledge about a topic
knows_about(NpcId, Topic) :-
    knows(NpcId, Topic).
knows_about(NpcId, Topic) :-
    knows(NpcId, Topic, _).

% ═══════════════════════════════════════════════════════════════════════════
% Pronunciation Tracking
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(pronunciation_score/4).
:- dynamic(pronunciation_passed/2).

% player_avg_pronunciation(Player, Avg) — average score across all attempts
player_avg_pronunciation(Player, Avg) :-
    findall(S, pronunciation_score(Player, _, S, _), Scores),
    Scores \\= [],
    insimul_sum_list(Scores, Total),
    length(Scores, Count),
    Avg is Total / Count.

% pronunciation_count(Player, Count) — number of distinct phrases practiced
pronunciation_count(Player, Count) :-
    findall(P, pronunciation_passed(Player, P), Phrases),
    length(Phrases, Count).

% pronunciation_above(Player, Threshold, Count) — phrases scoring above threshold
pronunciation_above(Player, Threshold, Count) :-
    findall(P, (pronunciation_score(Player, P, S, _), S >= Threshold), Phrases),
    length(Phrases, Count).

% ═══════════════════════════════════════════════════════════════════════════
% Assessment & NPC Exam Results
% ═══════════════════════════════════════════════════════════════════════════

:- dynamic(assessment_result/6).
:- dynamic(player_cefr_level/2).
:- dynamic(player_cefr_snapshot/3).
:- dynamic(player_dimension_score/3).
:- dynamic(phase_score/3).
:- dynamic(dimension_score/4).

% player_has_assessment(Player, ExamId) — has the player completed this exam?
player_has_assessment(Player, ExamId) :-
    assessment_result(Player, ExamId, _, _, _, _).

% assessment_score_pct(Player, ExamId, Pct) — score as percentage
assessment_score_pct(Player, ExamId, Pct) :-
    assessment_result(Player, ExamId, Score, MaxScore, _, _),
    MaxScore > 0,
    Pct is (Score * 100) / MaxScore.

% player_meets_cefr(Player, RequiredLevel) — does player meet a minimum CEFR?
% Uses CEFR level ordering (a1 < a2 < b1 < b2 < c1 < c2) via cefr_gte/2.
player_meets_cefr(Player, RequiredLevel) :-
    player_cefr_level(Player, ActualLevel),
    cefr_gte(ActualLevel, RequiredLevel).
`.trim();
