/**
 * Animation Registry — Complete catalog of all animations available
 * from Quaternius character models.
 *
 * Auto-generated by scanning GLB/GLTF files in:
 *   client/public/assets/models/characters/quaternius/
 *
 * Three animation sources:
 *   - anim_ual1_standard (45 animations) — primary locomotion/action pack
 *   - anim2_ual2_standard (43 animations) — combat/farming/zombie pack
 *   - char_* models (24 animations each) — embedded character animations
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type AnimationCategory =
  | 'locomotion'
  | 'social'
  | 'work'
  | 'leisure'
  | 'combat'
  | 'emote'
  | 'activity'
  | 'pose'
  | 'ranged'
  | 'magic';

export interface AnimationEntry {
  name: string;
  description: string;
  duration: number;
  loop: boolean;
  category: AnimationCategory;
}

// ---------------------------------------------------------------------------
// Model IDs — every model directory that contains at least one animation
// ---------------------------------------------------------------------------

const CHARACTER_MODELS = [
  'char_female_adventurer',
  'char_female_casual',
  'char_female_formal',
  'char_female_medieval',
  'char_female_punk',
  'char_female_soldier',
  'char_female_suit',
  'char_female_worker',
  'char_male_adventurer',
  'char_male_beach',
  'char_male_casual',
  'char_male_casual_hoodie',
  'char_male_farmer',
  'char_male_king',
  'char_male_punk',
  'char_male_suit',
  'char_male_swat',
  'char_male_worker',
] as const;

const ANIM_PACK_MODELS = [
  'anim_ual1_standard',
  'anim2_ual2_standard',
] as const;

export type CharacterModelId = (typeof CHARACTER_MODELS)[number];
export type AnimPackModelId = (typeof ANIM_PACK_MODELS)[number];
export type ModelId = CharacterModelId | AnimPackModelId;

export const ALL_MODEL_IDS: readonly ModelId[] = [
  ...CHARACTER_MODELS,
  ...ANIM_PACK_MODELS,
];

// ---------------------------------------------------------------------------
// Animation Catalog — every unique animation found across all models
// ---------------------------------------------------------------------------

export const ANIMATION_CATALOG: Record<string, AnimationEntry> = {
  // === POSE ===
  A_TPose: { name: 'A_TPose', description: 'T-pose reference stance', duration: 0, loop: false, category: 'pose' },

  // === LOCOMOTION ===
  Crouch_Fwd_Loop: { name: 'Crouch_Fwd_Loop', description: 'Crouching forward movement', duration: 1.0, loop: true, category: 'locomotion' },
  Crouch_Idle_Loop: { name: 'Crouch_Idle_Loop', description: 'Crouching idle stance', duration: 2.0, loop: true, category: 'locomotion' },
  ClimbUp_1m_RM: { name: 'ClimbUp_1m_RM', description: 'Climb up 1 meter ledge (root motion)', duration: 1.5, loop: false, category: 'locomotion' },
  Jog_Fwd_Loop: { name: 'Jog_Fwd_Loop', description: 'Jogging forward', duration: 0.8, loop: true, category: 'locomotion' },
  Jump_Land: { name: 'Jump_Land', description: 'Landing from jump', duration: 0.5, loop: false, category: 'locomotion' },
  Jump_Loop: { name: 'Jump_Loop', description: 'In-air jump loop', duration: 0.6, loop: true, category: 'locomotion' },
  Jump_Start: { name: 'Jump_Start', description: 'Jump takeoff', duration: 0.4, loop: false, category: 'locomotion' },
  NinjaJump_Idle_Loop: { name: 'NinjaJump_Idle_Loop', description: 'Ninja jump idle hover', duration: 1.0, loop: true, category: 'locomotion' },
  NinjaJump_Land: { name: 'NinjaJump_Land', description: 'Ninja jump landing', duration: 0.5, loop: false, category: 'locomotion' },
  NinjaJump_Start: { name: 'NinjaJump_Start', description: 'Ninja jump takeoff', duration: 0.4, loop: false, category: 'locomotion' },
  Roll: { name: 'Roll', description: 'Dodge roll', duration: 0.8, loop: false, category: 'locomotion' },
  Roll_RM: { name: 'Roll_RM', description: 'Dodge roll (root motion)', duration: 0.8, loop: false, category: 'locomotion' },
  Run: { name: 'Run', description: 'Running forward', duration: 0.7, loop: true, category: 'locomotion' },
  Run_Back: { name: 'Run_Back', description: 'Running backward', duration: 0.7, loop: true, category: 'locomotion' },
  Run_Left: { name: 'Run_Left', description: 'Strafing left', duration: 0.7, loop: true, category: 'locomotion' },
  Run_Right: { name: 'Run_Right', description: 'Strafing right', duration: 0.7, loop: true, category: 'locomotion' },
  Run_Shoot: { name: 'Run_Shoot', description: 'Running while shooting', duration: 0.7, loop: true, category: 'locomotion' },
  Slide_Exit: { name: 'Slide_Exit', description: 'Exit slide', duration: 0.4, loop: false, category: 'locomotion' },
  Slide_Loop: { name: 'Slide_Loop', description: 'Sliding loop', duration: 0.6, loop: true, category: 'locomotion' },
  Slide_Start: { name: 'Slide_Start', description: 'Start sliding', duration: 0.3, loop: false, category: 'locomotion' },
  Sprint_Loop: { name: 'Sprint_Loop', description: 'Sprinting forward', duration: 0.6, loop: true, category: 'locomotion' },
  Swim_Fwd_Loop: { name: 'Swim_Fwd_Loop', description: 'Swimming forward', duration: 1.2, loop: true, category: 'locomotion' },
  Swim_Idle_Loop: { name: 'Swim_Idle_Loop', description: 'Treading water', duration: 2.0, loop: true, category: 'locomotion' },
  Walk: { name: 'Walk', description: 'Walking forward', duration: 1.0, loop: true, category: 'locomotion' },
  Walk_Carry_Loop: { name: 'Walk_Carry_Loop', description: 'Walking while carrying object', duration: 1.0, loop: true, category: 'locomotion' },
  Walk_Formal_Loop: { name: 'Walk_Formal_Loop', description: 'Formal/dignified walk', duration: 1.2, loop: true, category: 'locomotion' },
  Walk_Loop: { name: 'Walk_Loop', description: 'Walking forward loop', duration: 1.0, loop: true, category: 'locomotion' },
  Push_Loop: { name: 'Push_Loop', description: 'Pushing object forward', duration: 1.0, loop: true, category: 'locomotion' },
  Driving_Loop: { name: 'Driving_Loop', description: 'Vehicle driving pose', duration: 2.0, loop: true, category: 'locomotion' },

  // === SOCIAL ===
  Idle: { name: 'Idle', description: 'Standard idle stance', duration: 2.0, loop: true, category: 'social' },
  Idle_Loop: { name: 'Idle_Loop', description: 'Idle breathing loop', duration: 3.0, loop: true, category: 'social' },
  Idle_FoldArms_Loop: { name: 'Idle_FoldArms_Loop', description: 'Idle with arms folded', duration: 3.0, loop: true, category: 'social' },
  Idle_Neutral: { name: 'Idle_Neutral', description: 'Neutral idle stance', duration: 2.0, loop: true, category: 'social' },
  Idle_No_Loop: { name: 'Idle_No_Loop', description: 'Single idle (no loop)', duration: 2.0, loop: false, category: 'social' },
  Idle_Talking_Loop: { name: 'Idle_Talking_Loop', description: 'Talking with gestures while standing', duration: 2.5, loop: true, category: 'social' },
  Idle_TalkingPhone_Loop: { name: 'Idle_TalkingPhone_Loop', description: 'Talking on phone while standing', duration: 2.5, loop: true, category: 'social' },
  Idle_Rail_Call: { name: 'Idle_Rail_Call', description: 'Calling out while leaning on rail', duration: 2.0, loop: false, category: 'social' },
  Idle_Rail_Loop: { name: 'Idle_Rail_Loop', description: 'Leaning on railing idle', duration: 3.0, loop: true, category: 'social' },
  Wave: { name: 'Wave', description: 'Waving greeting', duration: 1.5, loop: false, category: 'social' },
  Yes: { name: 'Yes', description: 'Nodding yes gesture', duration: 1.0, loop: false, category: 'social' },
  Interact: { name: 'Interact', description: 'Generic interaction gesture', duration: 1.0, loop: false, category: 'social' },
  Sitting_Talking_Loop: { name: 'Sitting_Talking_Loop', description: 'Talking while seated', duration: 2.5, loop: true, category: 'social' },

  // === WORK ===
  Fixing_Kneeling: { name: 'Fixing_Kneeling', description: 'Kneeling repair work', duration: 2.0, loop: true, category: 'work' },
  PickUp_Table: { name: 'PickUp_Table', description: 'Picking up item from table', duration: 1.2, loop: false, category: 'work' },
  TreeChopping_Loop: { name: 'TreeChopping_Loop', description: 'Chopping a tree', duration: 1.5, loop: true, category: 'work' },
  Chest_Open: { name: 'Chest_Open', description: 'Opening a chest', duration: 1.0, loop: false, category: 'work' },
  OverhandThrow: { name: 'OverhandThrow', description: 'Overhand throw', duration: 1.0, loop: false, category: 'work' },

  // === LEISURE ===
  Dance_Loop: { name: 'Dance_Loop', description: 'Dancing loop', duration: 2.0, loop: true, category: 'leisure' },
  Sitting_Enter: { name: 'Sitting_Enter', description: 'Transition to sitting', duration: 1.0, loop: false, category: 'leisure' },
  Sitting_Exit: { name: 'Sitting_Exit', description: 'Standing up from sitting', duration: 1.0, loop: false, category: 'leisure' },
  Sitting_Idle_Loop: { name: 'Sitting_Idle_Loop', description: 'Seated idle', duration: 3.0, loop: true, category: 'leisure' },
  Consume: { name: 'Consume', description: 'Eating/drinking consumable', duration: 2.0, loop: false, category: 'leisure' },
  LayToIdle: { name: 'LayToIdle', description: 'Getting up from lying down', duration: 1.5, loop: false, category: 'leisure' },
  Idle_Lantern_Loop: { name: 'Idle_Lantern_Loop', description: 'Holding lantern idle', duration: 3.0, loop: true, category: 'leisure' },
  Idle_Torch_Loop: { name: 'Idle_Torch_Loop', description: 'Holding torch idle', duration: 3.0, loop: true, category: 'leisure' },

  // === COMBAT ===
  Death: { name: 'Death', description: 'Death collapse', duration: 2.0, loop: false, category: 'combat' },
  Death01: { name: 'Death01', description: 'Death collapse variant', duration: 2.0, loop: false, category: 'combat' },
  HitRecieve: { name: 'HitRecieve', description: 'Taking hit reaction', duration: 0.5, loop: false, category: 'combat' },
  HitRecieve_2: { name: 'HitRecieve_2', description: 'Taking hit reaction variant', duration: 0.5, loop: false, category: 'combat' },
  Hit_Chest: { name: 'Hit_Chest', description: 'Chest hit reaction', duration: 0.5, loop: false, category: 'combat' },
  Hit_Head: { name: 'Hit_Head', description: 'Head hit reaction', duration: 0.5, loop: false, category: 'combat' },
  Hit_Knockback: { name: 'Hit_Knockback', description: 'Knockback from hit', duration: 0.8, loop: false, category: 'combat' },
  Hit_Knockback_RM: { name: 'Hit_Knockback_RM', description: 'Knockback from hit (root motion)', duration: 0.8, loop: false, category: 'combat' },
  Kick_Left: { name: 'Kick_Left', description: 'Left kick attack', duration: 0.8, loop: false, category: 'combat' },
  Kick_Right: { name: 'Kick_Right', description: 'Right kick attack', duration: 0.8, loop: false, category: 'combat' },
  Punch_Cross: { name: 'Punch_Cross', description: 'Cross punch', duration: 0.6, loop: false, category: 'combat' },
  Punch_Jab: { name: 'Punch_Jab', description: 'Jab punch', duration: 0.4, loop: false, category: 'combat' },
  Punch_Left: { name: 'Punch_Left', description: 'Left punch', duration: 0.6, loop: false, category: 'combat' },
  Punch_Right: { name: 'Punch_Right', description: 'Right punch', duration: 0.6, loop: false, category: 'combat' },
  Melee_Hook: { name: 'Melee_Hook', description: 'Melee hook attack', duration: 0.7, loop: false, category: 'combat' },
  Melee_Hook_Rec: { name: 'Melee_Hook_Rec', description: 'Melee hook recovery', duration: 0.5, loop: false, category: 'combat' },
  Sword_Attack: { name: 'Sword_Attack', description: 'Sword attack swing', duration: 0.8, loop: false, category: 'combat' },
  Sword_Attack_RM: { name: 'Sword_Attack_RM', description: 'Sword attack (root motion)', duration: 0.8, loop: false, category: 'combat' },
  Sword_Block: { name: 'Sword_Block', description: 'Sword block stance', duration: 0.5, loop: false, category: 'combat' },
  Sword_Dash_RM: { name: 'Sword_Dash_RM', description: 'Sword dash attack (root motion)', duration: 0.6, loop: false, category: 'combat' },
  Sword_Idle: { name: 'Sword_Idle', description: 'Sword ready idle', duration: 2.0, loop: true, category: 'combat' },
  Idle_Sword: { name: 'Idle_Sword', description: 'Idle with sword equipped', duration: 2.0, loop: true, category: 'combat' },
  Sword_Regular_A: { name: 'Sword_Regular_A', description: 'Sword combo hit A', duration: 0.6, loop: false, category: 'combat' },
  Sword_Regular_A_Rec: { name: 'Sword_Regular_A_Rec', description: 'Sword combo A recovery', duration: 0.4, loop: false, category: 'combat' },
  Sword_Regular_B: { name: 'Sword_Regular_B', description: 'Sword combo hit B', duration: 0.6, loop: false, category: 'combat' },
  Sword_Regular_B_Rec: { name: 'Sword_Regular_B_Rec', description: 'Sword combo B recovery', duration: 0.4, loop: false, category: 'combat' },
  Sword_Regular_C: { name: 'Sword_Regular_C', description: 'Sword combo hit C', duration: 0.6, loop: false, category: 'combat' },
  Sword_Regular_Combo: { name: 'Sword_Regular_Combo', description: 'Full sword combo chain', duration: 2.0, loop: false, category: 'combat' },
  Sword_Slash: { name: 'Sword_Slash', description: 'Single sword slash', duration: 0.7, loop: false, category: 'combat' },
  Shield_Dash_RM: { name: 'Shield_Dash_RM', description: 'Shield dash (root motion)', duration: 0.6, loop: false, category: 'combat' },
  Shield_OneShot: { name: 'Shield_OneShot', description: 'Shield bash attack', duration: 0.8, loop: false, category: 'combat' },
  Idle_Shield_Break: { name: 'Idle_Shield_Break', description: 'Shield break stagger', duration: 1.0, loop: false, category: 'combat' },
  Idle_Shield_Loop: { name: 'Idle_Shield_Loop', description: 'Shield guard idle', duration: 2.0, loop: true, category: 'combat' },
  Zombie_Idle_Loop: { name: 'Zombie_Idle_Loop', description: 'Zombie idle stance', duration: 3.0, loop: true, category: 'combat' },
  Zombie_Scratch: { name: 'Zombie_Scratch', description: 'Zombie scratch attack', duration: 1.0, loop: false, category: 'combat' },
  Zombie_Walk_Fwd_Loop: { name: 'Zombie_Walk_Fwd_Loop', description: 'Zombie shambling walk', duration: 1.5, loop: true, category: 'combat' },

  // === RANGED ===
  Gun_Shoot: { name: 'Gun_Shoot', description: 'Shooting gun', duration: 0.5, loop: false, category: 'ranged' },
  Idle_Gun: { name: 'Idle_Gun', description: 'Idle with gun lowered', duration: 2.0, loop: true, category: 'ranged' },
  Idle_Gun_Pointing: { name: 'Idle_Gun_Pointing', description: 'Idle aiming gun', duration: 2.0, loop: true, category: 'ranged' },
  Idle_Gun_Shoot: { name: 'Idle_Gun_Shoot', description: 'Standing gun fire', duration: 0.5, loop: false, category: 'ranged' },
  Pistol_Aim_Down: { name: 'Pistol_Aim_Down', description: 'Aiming pistol downward', duration: 1.0, loop: true, category: 'ranged' },
  Pistol_Aim_Neutral: { name: 'Pistol_Aim_Neutral', description: 'Aiming pistol forward', duration: 1.0, loop: true, category: 'ranged' },
  Pistol_Aim_Up: { name: 'Pistol_Aim_Up', description: 'Aiming pistol upward', duration: 1.0, loop: true, category: 'ranged' },
  Pistol_Idle_Loop: { name: 'Pistol_Idle_Loop', description: 'Pistol idle ready stance', duration: 2.0, loop: true, category: 'ranged' },
  Pistol_Reload: { name: 'Pistol_Reload', description: 'Reloading pistol', duration: 1.5, loop: false, category: 'ranged' },
  Pistol_Shoot: { name: 'Pistol_Shoot', description: 'Firing pistol', duration: 0.4, loop: false, category: 'ranged' },

  // === MAGIC ===
  Spell_Simple_Enter: { name: 'Spell_Simple_Enter', description: 'Begin spellcasting', duration: 0.8, loop: false, category: 'magic' },
  Spell_Simple_Exit: { name: 'Spell_Simple_Exit', description: 'End spellcasting', duration: 0.6, loop: false, category: 'magic' },
  Spell_Simple_Idle_Loop: { name: 'Spell_Simple_Idle_Loop', description: 'Spellcasting idle channeling', duration: 2.0, loop: true, category: 'magic' },
  Spell_Simple_Shoot: { name: 'Spell_Simple_Shoot', description: 'Cast spell projectile', duration: 0.5, loop: false, category: 'magic' },

  // === ACTIVITY ===
  Farm_Harvest: { name: 'Farm_Harvest', description: 'Harvesting crops', duration: 2.0, loop: false, category: 'activity' },
  Farm_PlantSeed: { name: 'Farm_PlantSeed', description: 'Planting seeds', duration: 1.5, loop: false, category: 'activity' },
  Farm_Watering: { name: 'Farm_Watering', description: 'Watering plants', duration: 2.0, loop: true, category: 'activity' },
};

// ---------------------------------------------------------------------------
// Animations embedded in each character model
// ---------------------------------------------------------------------------

const CHAR_MODEL_ANIMATIONS = [
  'Death', 'Gun_Shoot', 'HitRecieve', 'HitRecieve_2',
  'Idle', 'Idle_Gun', 'Idle_Gun_Pointing', 'Idle_Gun_Shoot',
  'Idle_Neutral', 'Idle_Sword', 'Interact',
  'Kick_Left', 'Kick_Right', 'Punch_Left', 'Punch_Right',
  'Roll', 'Run', 'Run_Back', 'Run_Left', 'Run_Right', 'Run_Shoot',
  'Sword_Slash', 'Walk', 'Wave',
] as const;

const UAL1_ANIMATIONS = [
  'A_TPose', 'Crouch_Fwd_Loop', 'Crouch_Idle_Loop', 'Dance_Loop',
  'Death01', 'Driving_Loop', 'Fixing_Kneeling', 'Hit_Chest', 'Hit_Head',
  'Idle_Loop', 'Idle_Talking_Loop', 'Idle_Torch_Loop', 'Interact',
  'Jog_Fwd_Loop', 'Jump_Land', 'Jump_Loop', 'Jump_Start',
  'PickUp_Table', 'Pistol_Aim_Down', 'Pistol_Aim_Neutral', 'Pistol_Aim_Up',
  'Pistol_Idle_Loop', 'Pistol_Reload', 'Pistol_Shoot',
  'Punch_Cross', 'Punch_Jab', 'Push_Loop', 'Roll', 'Roll_RM',
  'Sitting_Enter', 'Sitting_Exit', 'Sitting_Idle_Loop', 'Sitting_Talking_Loop',
  'Spell_Simple_Enter', 'Spell_Simple_Exit', 'Spell_Simple_Idle_Loop', 'Spell_Simple_Shoot',
  'Sprint_Loop', 'Swim_Fwd_Loop', 'Swim_Idle_Loop',
  'Sword_Attack', 'Sword_Attack_RM', 'Sword_Idle',
  'Walk_Formal_Loop', 'Walk_Loop',
] as const;

const UAL2_ANIMATIONS = [
  'A_TPose', 'Chest_Open', 'ClimbUp_1m_RM', 'Consume',
  'Farm_Harvest', 'Farm_PlantSeed', 'Farm_Watering',
  'Hit_Knockback', 'Hit_Knockback_RM',
  'Idle_FoldArms_Loop', 'Idle_Lantern_Loop', 'Idle_No_Loop',
  'Idle_Rail_Call', 'Idle_Rail_Loop', 'Idle_Shield_Break', 'Idle_Shield_Loop',
  'Idle_TalkingPhone_Loop', 'LayToIdle',
  'Melee_Hook', 'Melee_Hook_Rec',
  'NinjaJump_Idle_Loop', 'NinjaJump_Land', 'NinjaJump_Start',
  'OverhandThrow', 'Shield_Dash_RM', 'Shield_OneShot',
  'Slide_Exit', 'Slide_Loop', 'Slide_Start',
  'Sword_Block', 'Sword_Dash_RM',
  'Sword_Regular_A', 'Sword_Regular_A_Rec',
  'Sword_Regular_B', 'Sword_Regular_B_Rec',
  'Sword_Regular_C', 'Sword_Regular_Combo',
  'TreeChopping_Loop', 'Walk_Carry_Loop', 'Yes',
  'Zombie_Idle_Loop', 'Zombie_Scratch', 'Zombie_Walk_Fwd_Loop',
] as const;

const charModelEntries = Object.fromEntries(
  CHARACTER_MODELS.map(id => [id, CHAR_MODEL_ANIMATIONS as readonly string[]])
) as Record<CharacterModelId, readonly string[]>;

const MODEL_ANIMATION_MAP: Record<ModelId, readonly string[]> = {
  ...charModelEntries,
  anim_ual1_standard: UAL1_ANIMATIONS,
  anim2_ual2_standard: UAL2_ANIMATIONS,
};

// ---------------------------------------------------------------------------
// Lookup functions
// ---------------------------------------------------------------------------

export function getAvailableAnimations(modelId: string): string[] {
  const anims = MODEL_ANIMATION_MAP[modelId as ModelId];
  return anims ? [...anims] : [];
}

export function getModelsWithAnimation(animationName: string): string[] {
  return ALL_MODEL_IDS.filter(id => {
    const anims = MODEL_ANIMATION_MAP[id];
    return anims.some(a => a === animationName);
  });
}

export function getAnimationsByCategory(category: AnimationCategory): AnimationEntry[] {
  return Object.values(ANIMATION_CATALOG).filter(e => e.category === category);
}

// ---------------------------------------------------------------------------
// Summary — call logAnimationSummary() to print audit results
// ---------------------------------------------------------------------------

export function getAnimationSummary(): {
  totalUniqueAnimations: number;
  categoryCounts: Record<string, number>;
  modelAnimationCounts: Record<string, number>;
  richestModels: { modelId: string; count: number }[];
} {
  const categoryCounts: Record<string, number> = {};
  for (const entry of Object.values(ANIMATION_CATALOG)) {
    categoryCounts[entry.category] = (categoryCounts[entry.category] || 0) + 1;
  }

  const modelAnimationCounts: Record<string, number> = {};
  for (const id of ALL_MODEL_IDS) {
    modelAnimationCounts[id] = MODEL_ANIMATION_MAP[id].length;
  }

  const richestModels = ALL_MODEL_IDS
    .map(id => ({ modelId: id, count: MODEL_ANIMATION_MAP[id].length }))
    .sort((a, b) => b.count - a.count);

  return {
    totalUniqueAnimations: Object.keys(ANIMATION_CATALOG).length,
    categoryCounts,
    modelAnimationCounts,
    richestModels,
  };
}

export function logAnimationSummary(): void {
  const summary = getAnimationSummary();
  for (const [cat, count] of Object.entries(summary.categoryCounts).sort((a, b) => b[1] - a[1])) {
  }
  for (const { modelId, count } of summary.richestModels.slice(0, 5)) {
  }
}
