// emit-csharp.mjs — emit C# DTOs (System.Text.Json) for the core save/world schemas.
//
// Target: packages/unity/Runtime/Generated/InsimulGenerated.cs
// Namespace: Insimul.Generated   (nullable-aware, [JsonPropertyName] attributes)
//
// Covers SaveFile, SaveFileEnvelope, WorldIR (+ their nested types) in one file so
// quicktype's shared serialization helpers are emitted exactly once. See
// build-merged-schema.mjs for why a single merged document is used.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildMergedSchema, ROOT_TYPE_NAME } from './build-merged-schema.mjs';
import { runQuicktypeOnSchema } from './quicktype-runner.mjs';

const NAMESPACE = 'Insimul.Generated';
const OUT_FILE = 'InsimulGenerated.cs';

const BANNER = [
  '// -----------------------------------------------------------------------------',
  '// <auto-generated>',
  '//   GENERATED FILE — DO NOT EDIT BY HAND.',
  '//   Regenerate with:  npm run codegen   (from the insimul-runtime root)',
  '//   Source of truth:  packages/core/schemas/{save-file,save-envelope,world-ir}.schema.json',
  '//   Emitter:          tools/codegen/emit-csharp.mjs (quicktype, System.Text.Json)',
  '// </auto-generated>',
  '// -----------------------------------------------------------------------------',
  '',
].join('\n');

/**
 * Generate the C# DTO source text (deterministic; no filesystem writes).
 * @returns {string}
 */
export function generateCSharp() {
  const schema = buildMergedSchema();
  const body = runQuicktypeOnSchema(schema, [
    '--lang',
    'cs',
    '--namespace',
    NAMESPACE,
    '--framework',
    'SystemTextJson',
    '--top-level',
    ROOT_TYPE_NAME,
  ]);
  // Normalize trailing whitespace to a single newline for stable byte output.
  return BANNER + body.replace(/\s*$/, '') + '\n';
}

/**
 * Write the C# DTOs under `baseDir` (default: repo root) and return written paths.
 * @param {string} baseDir  base directory the package tree hangs off of
 * @returns {string[]} relative paths (from baseDir) written
 */
export function emitCSharp(baseDir) {
  const relDir = join('packages', 'unity', 'Runtime', 'Generated');
  const outDir = join(baseDir, relDir);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, OUT_FILE), generateCSharp());
  return [join(relDir, OUT_FILE)];
}
