/**
 * Game Genre Registry
 * 
 * Central registry for all game genre configurations.
 * Maps game types to their specific camera, movement, combat, and feature settings.
 */

import { GenreConfig, GenreRegistry } from './types';

const defaultFeatures = {
  inventory: true,
  crafting: false,
  dialogue: true,
  combat: true,
  building: false,
  resources: false,
  permadeath: false,
  quests: true,
  experience: true,
  skills: true,
};

export const GENRE_REGISTRY: GenreRegistry = {
  'rpg': {
    id: 'rpg',
    name: 'RPG',
    description: 'Role-playing game with character progression, quests, and story',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'melee',
    movementStyle: 'free',
    uiLayout: 'action_rpg',
    defaultWorldType: 'medieval-fantasy',
    features: {
      ...defaultFeatures,
      inventory: true,
      crafting: true,
    },
    questTypes: ['rpg'],
    difficultyLevels: ['easy', 'normal', 'hard', 'legendary'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: true,
    showStaminaBar: true,
    showAmmoCounter: false,
    showCompass: true,
  },

  'action': {
    id: 'action',
    name: 'Action',
    description: 'Fast-paced combat and reflexes',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'melee',
    movementStyle: 'free',
    uiLayout: 'action_rpg',
    defaultWorldType: 'medieval-fantasy',
    features: {
      ...defaultFeatures,
      crafting: false,
    },
    questTypes: ['rpg'],
    difficultyLevels: ['easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.2,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: false,
    showHealthBar: true,
    showStaminaBar: true,
    showAmmoCounter: false,
    showCompass: false,
  },

  'fighting': {
    id: 'fighting',
    name: 'Fighting',
    description: 'One-on-one combat with combos and special moves',
    cameraMode: 'fighting',
    movementPlane: 'xy',
    controlScheme: 'wasd_mouse',
    combatStyle: 'melee',
    movementStyle: 'free',
    uiLayout: 'minimal',
    defaultWorldType: 'generic',
    features: {
      ...defaultFeatures,
      inventory: false,
      dialogue: false,
      quests: false,
      experience: false,
      skills: false,
    },
    questTypes: [],
    difficultyLevels: ['easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.2,
    gravityMultiplier: 1.0,
    showMinimap: false,
    showHealthBar: true,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: false,
  },

  'platformer': {
    id: 'platformer',
    name: 'Platformer',
    description: 'Jumping and navigating levels',
    cameraMode: 'side_scroll',
    movementPlane: 'xy',
    controlScheme: 'wasd_mouse',
    combatStyle: 'melee',
    movementStyle: 'platformer',
    uiLayout: 'platformer',
    defaultWorldType: 'generic',
    features: {
      ...defaultFeatures,
      inventory: false,
      dialogue: false,
      combat: false,
    },
    questTypes: ['platformer'],
    difficultyLevels: ['easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.5,
    gravityMultiplier: 1.2,
    showMinimap: false,
    showHealthBar: true,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: false,
  },

  'strategy': {
    id: 'strategy',
    name: 'Strategy',
    description: 'Tactical decision-making and resource management',
    cameraMode: 'isometric',
    movementPlane: 'free',
    controlScheme: 'point_click',
    combatStyle: 'none',
    movementStyle: 'grid',
    uiLayout: 'rts',
    defaultWorldType: 'medieval-fantasy',
    features: {
      ...defaultFeatures,
      inventory: false,
      combat: false,
      building: true,
      resources: true,
    },
    questTypes: ['strategy'],
    difficultyLevels: ['easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: false,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: false,
  },

  'survival': {
    id: 'survival',
    name: 'Survival',
    description: 'Resource gathering, crafting, and survival mechanics',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'hybrid',
    movementStyle: 'free',
    uiLayout: 'action_rpg',
    defaultWorldType: 'post-apocalyptic',
    features: {
      ...defaultFeatures,
      inventory: true,
      crafting: true,
      building: true,
      resources: true,
    },
    questTypes: ['survival'],
    difficultyLevels: ['easy', 'normal', 'hard', 'hardcore'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: true,
    showStaminaBar: true,
    showAmmoCounter: false,
    showCompass: true,
  },

  'shooter': {
    id: 'shooter',
    name: 'Shooter',
    description: 'Ranged combat and precision shooting',
    cameraMode: 'first_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'ranged',
    movementStyle: 'free',
    uiLayout: 'fps',
    defaultWorldType: 'cyberpunk',
    features: {
      ...defaultFeatures,
      inventory: true,
      dialogue: false,
    },
    questTypes: ['shooter'],
    difficultyLevels: ['easy', 'normal', 'hard', 'nightmare'],
    defaultPlayerSpeed: 1.1,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: true,
    showStaminaBar: false,
    showAmmoCounter: true,
    showCompass: true,
  },

  'sandbox': {
    id: 'sandbox',
    name: 'Sandbox',
    description: 'Open-world exploration and creativity',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'hybrid',
    movementStyle: 'free',
    uiLayout: 'action_rpg',
    defaultWorldType: 'generic',
    features: {
      ...defaultFeatures,
      inventory: true,
      crafting: true,
      building: true,
      resources: true,
      quests: false,
    },
    questTypes: [],
    difficultyLevels: ['creative', 'easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: true,
    showStaminaBar: true,
    showAmmoCounter: false,
    showCompass: true,
  },

  'city-building': {
    id: 'city-building',
    name: 'City Building',
    description: 'Urban planning and city management',
    cameraMode: 'top_down',
    movementPlane: 'free',
    controlScheme: 'point_click',
    combatStyle: 'none',
    movementStyle: 'free',
    uiLayout: 'rts',
    defaultWorldType: 'generic',
    features: {
      ...defaultFeatures,
      inventory: false,
      dialogue: false,
      combat: false,
      building: true,
      resources: true,
      quests: false,
      experience: false,
      skills: false,
    },
    questTypes: [],
    difficultyLevels: ['easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: false,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: false,
  },

  'simulation': {
    id: 'simulation',
    name: 'Simulation',
    description: 'Realistic systems and life simulation',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'none',
    movementStyle: 'free',
    uiLayout: 'minimal',
    defaultWorldType: 'generic',
    features: {
      ...defaultFeatures,
      inventory: true,
      combat: false,
    },
    questTypes: ['rpg'],
    difficultyLevels: ['easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: false,
    showHealthBar: false,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: false,
  },

  'puzzle': {
    id: 'puzzle',
    name: 'Puzzle',
    description: 'Logic challenges and problem-solving',
    cameraMode: 'isometric',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'none',
    movementStyle: 'free',
    uiLayout: 'puzzle',
    defaultWorldType: 'generic',
    features: {
      ...defaultFeatures,
      inventory: false,
      combat: false,
      experience: false,
      skills: false,
    },
    questTypes: ['puzzle'],
    difficultyLevels: ['easy', 'normal', 'hard', 'expert'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: false,
    showHealthBar: false,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: false,
  },

  'language-learning': {
    id: 'language-learning',
    name: 'Language Learning',
    description: 'Educational game focused on vocabulary and grammar',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'none',
    movementStyle: 'free',
    uiLayout: 'minimal',
    defaultWorldType: 'historical',
    features: {
      ...defaultFeatures,
      inventory: true,
      combat: false,
      crafting: true,
    },
    questTypes: ['language-learning'],
    difficultyLevels: ['beginner', 'intermediate', 'advanced'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: false,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: true,
  },

  'educational': {
    id: 'educational',
    name: 'Educational',
    description: 'Learning experiences through gameplay',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'none',
    movementStyle: 'free',
    uiLayout: 'minimal',
    defaultWorldType: 'historical',
    features: {
      ...defaultFeatures,
      inventory: false,
      combat: false,
      crafting: false,
    },
    questTypes: ['language-learning'],
    difficultyLevels: ['beginner', 'intermediate', 'advanced'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: false,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: true,
  },

  'adventure': {
    id: 'adventure',
    name: 'Adventure',
    description: 'Exploration, narrative, and puzzle-solving',
    cameraMode: 'third_person',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'melee',
    movementStyle: 'free',
    uiLayout: 'action_rpg',
    defaultWorldType: 'tropical-pirate',
    features: {
      ...defaultFeatures,
      inventory: true,
    },
    questTypes: ['rpg'],
    difficultyLevels: ['easy', 'normal', 'hard'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 1.0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: true,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: true,
  },

  'roguelike': {
    id: 'roguelike',
    name: 'Roguelike',
    description: 'Procedural generation and permadeath',
    cameraMode: 'top_down',
    movementPlane: 'free',
    controlScheme: 'wasd_mouse',
    combatStyle: 'hybrid',
    movementStyle: 'grid',
    uiLayout: 'action_rpg',
    defaultWorldType: 'dark-fantasy',
    features: {
      ...defaultFeatures,
      inventory: true,
      permadeath: true,
    },
    questTypes: ['rpg'],
    difficultyLevels: ['normal', 'hard', 'nightmare'],
    defaultPlayerSpeed: 1.0,
    defaultJumpHeight: 0,
    gravityMultiplier: 1.0,
    showMinimap: true,
    showHealthBar: true,
    showStaminaBar: false,
    showAmmoCounter: false,
    showCompass: false,
  },
};

/**
 * Get genre configuration for a game type
 */
export function getGenreConfig(gameType: string): GenreConfig {
  return GENRE_REGISTRY[gameType] || GENRE_REGISTRY['rpg'];
}

/**
 * Get all available game genres
 */
export function getAllGenres(): GenreConfig[] {
  return Object.values(GENRE_REGISTRY);
}

/**
 * Check if a game type is valid
 */
export function isValidGameType(gameType: string): boolean {
  return gameType in GENRE_REGISTRY;
}

export * from './types';
